# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13df7349b52e680367f9843ce7f2be32"
name = "Pet Matcher: Product Match"
application_url = "https://pet-matcher-773884090352.europe-west1.run.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

compliance_urls = { privacy_policy_url = "https://pet-matcher-773884090352.europe-west1.run.app/privacy" }

[webhooks]
api_version = "2026-01"



  [[webhooks.subscriptions]]
  topics = [ "products/delete", "products/update", "products/create" ]
  uri = "/webhooks/products"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscription_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/privacy"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,write_customers,write_products"

[auth]
redirect_urls = [
  "https://pet-matcher-773884090352.europe-west1.run.app/auth/callback",
  "https://pet-matcher-773884090352.europe-west1.run.app/app/billing",
  "https://pet-matcher-773884090352.europe-west1.run.app/app"
]

[app_proxy]
url = "https://pet-matcher-773884090352.europe-west1.run.app/app"
subpath = "pet-matcher-final"
prefix = "apps"
